Use nanoseconds in string to date time conversions
log2timeline/dfdatetime pull request #270
Opened 2023-12-10 09:04 UTC by joachimmetz

2023-12-11 13:13 UTC, sydp requested changes
I left some thoughts for your consideration.

Thanks for adding this, it should help address my other issue on plaso.

2023-12-12 05:51 UTC, joachimmetz commented on dfdatetime/cocoa_time.py
>            YYYY-MM-DD hh:mm:ss.######[+-]##:##
I'll keep it with 6 given that the docstring can be 3, 6 or 9 and a notation like `#{3,6,9}` might be more confusing

2023-12-12 05:52 UTC, joachimmetz commented on dfdatetime/dotnet_datetime.py
> +    nanoseconds, _ = divmod(nanoseconds, 100)
could but divmod is the standard used elsewhere in the codebase

2023-12-12 05:54 UTC, joachimmetz commented on dfdatetime/fat_date_time.py
> +    timestamp += milliseconds
could but divmod is used elsewhere

2023-12-12 05:56 UTC, joachimmetz commented on tests/precisions.py
> +  def testCopNanoosecondsToFractionOfSecond(self):
good catch, changed.

2023-12-12 10:27 UTC, sydp approved these changes
lgtm

2023-12-14 04:19 UTC, joachimmetz commented
I'll merge the changes after the next Plaso release

2023-12-27 06:10 UTC, merged